### ISSUE TITLE
Design interface

### ISSUE THREAD

**Issue by EwelinaLasowy** [blumilksoftware/escooters#14]
The aim of this task is to create some design in Figma or Adobe XD tool. Remember that application should looks good on full HD screens, tablets and phones.

**Comment by brzozka** [comment]
Design of the app is available at [https://www.figma.com/file/DYpKZfUvnOfpbKzGBc1d8X/e-scooters?type=design&node-id=0%3A1&t=nTNaHPNqW5mdlwdH-1](url)
Flow of the figma project [https://www.figma.com/proto/DYpKZfUvnOfpbKzGBc1d8X/e-scooters?type=design&node-id=28-683&scaling=contain&page-id=0%3A1&starting-point-node-id=28%3A683&show-proto-sidebar=1](url)

Currently there is concept of desktop app interface as well as mobile.

Admin panel as well as logged user panel is not finished yet.
