### ISSUE TITLE
Multiplatform app compatibility 

### ISSUE THREAD

**Issue by Lee0z** [blumilksoftware/escooters#166]
I've tried to run project in my main enviroment which is Windows 11. There is one main issue, `npm run dev` doesn't work as intended inside container.

I'm using Docker Desktop and WSL2 (ubuntu 22.04).

Traefik is indeed working in Windows browser:
![image](https://github.com/blumilksoftware/escooters/assets/102246039/a9315d93-215d-4a3a-ab85-d46baec1815c)

But there is problem with our project:
- Terminal output is fine:
![image](https://github.com/blumilksoftware/escooters/assets/102246039/dc4772ec-c295-4075-ba73-83c462ace465)

- App isn't responding:
(escooters.blumilk.localhost)
![image](https://github.com/blumilksoftware/escooters/assets/102246039/0f99b232-c25c-4e4b-a43a-f5081962d000)
(Vite dev server)
![image](https://github.com/blumilksoftware/escooters/assets/102246039/37f1296d-23f5-41b3-a6ee-d159f3da2271)

I asked my friend to try it in his enviroment (MacOS / Macbook Air M1) and he faced same issues as mine.

**Comment by mtracz** [comment]
@Lee0z 
What server's IP/port is listed in service in the Traefik? (Servers section)

![image](https://github.com/blumilksoftware/escooters/assets/22484267/2d984b4c-b9cd-4511-88c7-2701499587ab)

**Comment by Lee0z** [comment]
Server's IP/port is: 172.18.0.4:80
<img width="698" alt="image" src="https://github.com/blumilksoftware/escooters/assets/102246039/5e2a9d71-fde3-49dd-84f3-795de77f2098">

The address for Vite client is the same as in terminal.
![image](https://github.com/blumilksoftware/escooters/assets/102246039/aa8ed42a-67e0-40de-8cec-4fdacb2005da)
<img width="265" alt="image" src="https://github.com/blumilksoftware/escooters/assets/102246039/586edb86-28d2-4e51-afa7-64988b5f821d">

I've seen these docs and didn't manage to fix any issue:
- changed port proxy,
- the host is actually set in vite.config.js as:
```js
        server: {
            host: Object.values(networkInterfaces()).flat().find(i => i.family === 'IPv4' && !i.internal).address,
            port: process.env.VITE_PORT,
        },
``` 
- there was a tip to add usePooling boolean in vite.config.js too, but didn't help either.

**Comment by AleksandraKozubal** [comment]
There is no need to keep this issue open, so I'm closing it.
