### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by EwelinaLasowy** [blumilksoftware/escooters#2]
As not logged user I'd to see:
- on the right - map
- on the left - image of escooter, some app description and maybe login/register form?
It's only proposition - we're open to suggestions. 

Based on geolocalization (just the country is sufficient) map should be centered to the country and display the cities that are saved in database and are active (where scooters can be rented). The basic functionality is to show where rentals are available. It is optional to display the specific providers, like it is in old app.

It should include search functionality based on country and provider.

**Comment by brzozka** [comment]
For now this is just a concept of main page with sample functionality created in figma. Colors as well as placement of object can and probably will be changed. I am open for any kind of suggestion about design of the main page.
Figma project available at [https://www.figma.com/file/DYpKZfUvnOfpbKzGBc1d8X/e-scooters?type=design&node-id=0%3A1&t=nTNaHPNqW5mdlwdH-1](url)
Figma example flow [https://www.figma.com/proto/DYpKZfUvnOfpbKzGBc1d8X/e-scooters?type=design&node-id=28-683&scaling=scale-down&page-id=0%3A1&starting-point-node-id=28%3A683&show-proto-sidebar=1](url)

1.Main/Landing page
![Screenshot 2023-06-06 at 15-00-03 Figma](https://github.com/blumilksoftware/escooters/assets/39692087/08097184-c3a4-4a2d-a536-06f9a0ab3675)

2.Login form/register form
![Screenshot 2023-06-06 at 15-01-30 Figma](https://github.com/blumilksoftware/escooters/assets/39692087/4ca34305-b156-4e4f-acc3-fda5781f728e)

3. Main/Landing page mobile version
![Screenshot 2023-06-06 at 15-07-38 Figma](https://github.com/blumilksoftware/escooters/assets/39692087/9ee925f6-bd05-44c1-89b0-5b901cfce828)
