### ISSUE TITLE
[Administrator panel] CRUD for cities

### ISSUE THREAD

**Issue by EwelinaSkrzypacz** [blumilksoftware/escooters#5]
Administrator should be able to manage cities. Each city should has own coordinates. To simplify, we assume that one city can be assigned to only one country. 
Also changing provider should be possible from this level.

**Comment by EwelinaLasowy** [comment]
Also we should remember that in some providers is city "Gdańsk", somewhere "Gdansk", "Trójmiasto" and "Tricity".  Adding field with alternative city names will be a good idea.
